apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:
      attributes:
        actions:
          - key: service.name
            from_attribute: service
            action: insert
          - key: log.type
            from_attribute: log_type
            action: insert
          - key: host.name
            from_attribute: host
            action: insert

    exporters:
      logging:
        loglevel: debug
      
      loki:
        endpoint: http://loki-gateway.loki-system.svc.cluster.local/loki/api/v1/push
        tenant_id: operational
        default_labels_enabled:
          exporter: false
          job: true

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [logging, loki]
