apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:
      attributes:
        actions:
          - key: service.name
            from_attribute: service
            action: insert
          - key: log.type
            from_attribute: log_type
            action: insert
          - key: host.name
            from_attribute: host
            action: insert

    exporters:
      debug:
        verbosity: detailed
      
      loki:
        endpoint: http://loki.loki-system.svc.cluster.local:3100/loki/api/v1/push
        tenant_id: ""
        default_labels_enabled:
          exporter: false
          job: true
        labels:
          attributes:
            service.name: "service_name"
            log.type: "log_type"
            host.name: "host_name"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [debug, loki]
