name: observable-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  # Core runtime
  - python=3.11
  - nodejs=20
  - npm
  
  # Data processing and analysis
  - polars>=0.20.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  
  # HTTP and API clients
  - requests>=2.31.0
  - urllib3>=2.0.0
  
  # Data visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.17.0
  
  # Date and time handling
  - python-dateutil>=2.8.0
  
  # JSON processing (faster than stdlib)
  - orjson>=3.9.0
  
  # Monitoring and metrics
  - prometheus_client>=0.17.0
  
  # Additional conda packages
  - beautifulsoup4  # For web scraping if needed
  - lxml           # XML/HTML processing
  - pyarrow        # For Parquet files
  - fastapi        # If you want to add REST APIs
  - uvicorn        # ASGI server
  
  # Pip-only packages
  - pip
  - pip:
    # Observable Framework (must be installed via npm, not pip)
    # Add any pip-only packages here
    - streamlit      # Alternative dashboard framework
    - dash           # Alternative dashboard framework
    - great-expectations  # Data quality testing
    
# Usage Instructions:
# 1. To add conda packages: Add them under 'dependencies:' section
# 2. To add pip packages: Add them under 'pip:' section  
# 3. Commit changes to trigger GitOps deployment
# 4. Rebuild Docker image or restart pods to install new packages

# Example additions:
# For time series analysis:
# - statsmodels
# - scikit-learn
# - prophet

# For database connectivity:
# - sqlalchemy
# - psycopg2
# - pymongo

# For cloud integrations:
# - boto3          # AWS
# - azure-storage  # Azure
# - google-cloud-storage  # GCP