name: observable-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nodejs>=18
  - npm
  - pip
  - polars>=0.20.0
  - pandas>=2.0.0
  - requests>=2.31.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pip:
    - orjson>=3.9.0
    - prometheus-client>=0.17.0
    - python-dateutil>=2.8.0