apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Simplified Observable Framework deployment (no ConfigMaps)
  - observable-deployment.yaml
  - observable-service.yaml
  - observable-ingress.yaml
  
  # Auto-building system with OTEL integration
  - tekton-pipeline-otel.yaml
  - tekton-logs-forwarder.yaml
  - tekton-rbac.yaml

namespace: observable

labels:
  - pairs:
      app: observable
      component: dashboard

# Note: For conda-based deployment, you'll need to:
# 1. Build the Docker image from the Dockerfile
# 2. Push to a registry accessible by your cluster
# 3. Update the image in conda-deployment.yaml