---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observable-config
  namespace: observable
data:
  start.sh: |
    #!/bin/sh
    set -e
    npm install -g http-server
    cd /app
    mkdir -p public
    
    # Create main index page
    cat > public/index.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Observability Dashboard</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }
            h1 { color: #2c3e50; }
            .nav { margin: 20px 0; padding: 15px; background: #ecf0f1; border-radius: 6px; }
            .nav a { margin-right: 20px; text-decoration: none; color: #3498db; font-weight: bold; }
            .links { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }
            .link-card { padding: 20px; background: #3498db; color: white; text-decoration: none; border-radius: 6px; }
            .link-card:hover { background: #2980b9; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🔍 Observability Dashboard</h1>
            
            <div class="nav">
                <a href="/">Home</a>
                <a href="/security">Security Analysis</a>
                <a href="/operations">Operations</a>
            </div>
            
            <h2>Quick Access</h2>
            <div class="links">
                <a href="http://grafana.k3s.local" class="link-card">
                    <h3>📊 Grafana</h3>
                    <p>Operational monitoring</p>
                </a>
                <a href="http://quickwit.k3s.local/ui/search" class="link-card">
                    <h3>🔍 Quickwit</h3>
                    <p>Security log search</p>
                </a>
                <a href="http://argocd.k3s.local" class="link-card">
                    <h3>🚀 ArgoCD</h3>
                    <p>GitOps management</p>
                </a>
                <a href="http://loki.k3s.local" class="link-card">
                    <h3>📝 Loki API</h3>
                    <p>Log aggregation</p>
                </a>
            </div>
            
            <h2>Data Sources</h2>
            <ul>
                <li><strong>Loki:</strong> http://192.168.122.27:3100 - Operational logs</li>
                <li><strong>Quickwit:</strong> http://192.168.122.27:7280 - Security logs</li>
                <li><strong>Prometheus:</strong> http://192.168.122.27:9090 - Metrics</li>
            </ul>
            
            <h2>GitOps Workflow</h2>
            <p><strong>To add new dashboards:</strong></p>
            <ol>
                <li>Edit <code>apps/observable/minimal.yaml</code> ConfigMap</li>
                <li>Add new HTML files under the <code>start.sh</code> script</li>
                <li>Commit and push to trigger ArgoCD deployment</li>
                <li>Access at <code>http://observable.k3s.local/your-page</code></li>
            </ol>
            
            <footer style="margin-top: 40px; text-align: center; color: #7f8c8d;">
                <p>Built with Observable Framework for observability-k8s</p>
                <p>GitOps enabled - Add dashboards via ConfigMap</p>
            </footer>
        </div>
    </body>
    </html>
    EOF
    
    # Create security dashboard
    cat > public/security.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Security Dashboard</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }
            .nav { margin: 20px 0; padding: 15px; background: #ecf0f1; border-radius: 6px; }
            .nav a { margin-right: 20px; text-decoration: none; color: #3498db; font-weight: bold; }
            .metric-card { padding: 20px; background: #fff; border: 1px solid #ddd; border-radius: 6px; margin: 10px 0; }
            .status { padding: 10px; border-radius: 4px; margin: 10px 0; }
            .status.loading { background: #fff3cd; border-left: 4px solid #ffc107; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🛡️ Security Analysis Dashboard</h1>
            
            <div class="nav">
                <a href="/">Home</a>
                <a href="/security">Security Analysis</a>
                <a href="/operations">Operations</a>
            </div>
            
            <div class="status loading">
                <strong>Note:</strong> This is a static placeholder. For full Python-powered analytics with real-time data from Quickwit, 
                follow the GitOps workflow in the README to implement Observable Framework with data loaders.
            </div>
            
            <div class="metric-card">
                <h3>Security Event Analysis</h3>
                <p>Real-time security event analysis using Quickwit logs and advanced Python analytics.</p>
                <ul>
                    <li>Risk score calculation and distribution</li>
                    <li>Anomaly detection with scoring</li>
                    <li>Source IP analysis and categorization</li>
                    <li>Time-based security event patterns</li>
                    <li>Automated security recommendations</li>
                </ul>
            </div>
            
            <div class="metric-card">
                <h3>Quick Access</h3>
                <ul>
                    <li><a href="http://quickwit.k3s.local/ui/search">Quickwit Search Interface</a></li>
                    <li><a href="http://grafana.k3s.local">Grafana Security Dashboards</a></li>
                </ul>
            </div>
            
            <div class="metric-card">
                <h3>To Enable Full Analytics</h3>
                <p>Follow the complete workflow in the README:</p>
                <ol>
                    <li>Build the conda-based Docker image</li>
                    <li>Update deployment to use the custom image</li>
                    <li>Deploy with Python data loaders</li>
                    <li>Access real-time analytics and visualizations</li>
                </ol>
            </div>
        </div>
    </body>
    </html>
    EOF
    
    # Create operations dashboard
    cat > public/operations.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Operations Dashboard</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }
            .nav { margin: 20px 0; padding: 15px; background: #ecf0f1; border-radius: 6px; }
            .nav a { margin-right: 20px; text-decoration: none; color: #3498db; font-weight: bold; }
            .metric-card { padding: 20px; background: #fff; border: 1px solid #ddd; border-radius: 6px; margin: 10px 0; }
            .status { padding: 10px; border-radius: 4px; margin: 10px 0; }
            .status.loading { background: #fff3cd; border-left: 4px solid #ffc107; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>⚙️ Operations Dashboard</h1>
            
            <div class="nav">
                <a href="/">Home</a>
                <a href="/security">Security Analysis</a>
                <a href="/operations">Operations</a>
            </div>
            
            <div class="status loading">
                <strong>Note:</strong> This is a static placeholder. For full Python-powered analytics with real-time data from Loki and Prometheus, 
                follow the GitOps workflow in the README to implement Observable Framework with data loaders.
            </div>
            
            <div class="metric-card">
                <h3>System Performance Analysis</h3>
                <p>Advanced operational analytics using Loki logs and Prometheus metrics with Python processing.</p>
                <ul>
                    <li>System health overview with health indicators</li>
                    <li>Resource utilization monitoring</li>
                    <li>Log level distribution and trends</li>
                    <li>Service activity analysis with error rates</li>
                    <li>Performance metrics and recommendations</li>
                </ul>
            </div>
            
            <div class="metric-card">
                <h3>Quick Access</h3>
                <ul>
                    <li><a href="http://grafana.k3s.local">Grafana Operational Dashboards</a></li>
                    <li><a href="http://loki.k3s.local">Loki API Direct Access</a></li>
                    <li><a href="http://192.168.122.27:9090">Prometheus Metrics</a></li>
                </ul>
            </div>
            
            <div class="metric-card">
                <h3>To Enable Full Analytics</h3>
                <p>Follow the complete workflow in the README:</p>
                <ol>
                    <li>Build the conda-based Docker image</li>
                    <li>Update deployment to use the custom image</li>
                    <li>Deploy with Python data loaders</li>
                    <li>Access real-time analytics and visualizations</li>
                </ol>
            </div>
        </div>
    </body>
    </html>
    EOF
    
    http-server public -p 3000 -a 0.0.0.0
