---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observable-config
  namespace: observable
data:
  start.sh: |
    #!/bin/sh
    set -e
    
    # Install simple HTTP server
    npm install -g http-server
    
    # Create web content
    cd /app
    mkdir -p public
    cp /config/index.html public/
    cp /config/style.css public/
    
    # Start HTTP server
    http-server public -p 3000 -a 0.0.0.0
  
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Observability Dashboard</title>
        <link rel="stylesheet" href="style.css">
        <script src="https://d3js.org/d3.v7.min.js"></script>
    </head>
    <body>
        <header>
            <h1>🔍 Observability Dashboard</h1>
            <p>Real-time monitoring and analysis for your observability stack</p>
        </header>
        
        <main>
            <section class="quick-links">
                <h2>Quick Access</h2>
                <div class="links-grid">
                    <a href="http://grafana.k3s.local" class="service-link grafana">
                        <h3>📊 Grafana</h3>
                        <p>Operational monitoring and dashboards</p>
                    </a>
                    <a href="http://quickwit.k3s.local/ui/search" class="service-link quickwit">
                        <h3>🔍 Quickwit</h3>
                        <p>Security log search and analysis</p>
                    </a>
                    <a href="http://argocd.k3s.local" class="service-link argocd">
                        <h3>🚀 ArgoCD</h3>
                        <p>GitOps deployment management</p>
                    </a>
                    <a href="http://loki.k3s.local" class="service-link loki">
                        <h3>📝 Loki</h3>
                        <p>Log aggregation API</p>
                    </a>
                </div>
            </section>
            
            <section class="data-sources">
                <h2>Data Sources</h2>
                <div class="sources-grid">
                    <div class="source-card">
                        <h3>Loki</h3>
                        <p>Operational logs and time-series data</p>
                        <span class="endpoint">192.168.122.27:3100</span>
                    </div>
                    <div class="source-card">
                        <h3>Quickwit</h3>
                        <p>Security logs and full-text search</p>
                        <span class="endpoint">192.168.122.27:7280</span>
                    </div>
                    <div class="source-card">
                        <h3>Prometheus</h3>
                        <p>Metrics and monitoring data</p>
                        <span class="endpoint">192.168.122.27:9090</span>
                    </div>
                </div>
            </section>
            
            <section class="architecture">
                <h2>Architecture Flow</h2>
                <div class="architecture-diagram">
                    <pre>
Vector/Clients → OpenTelemetry Collector → {Loki (operational), Quickwit (security)}
                           ↓                    ↓                    ↓
                   Grafana (dashboards)  Quickwit UI (search)  Observable (reports)
                           ↓                                        ↓
                  Prometheus (metrics)                    Data analysis
                    </pre>
                </div>
            </section>
            
            <section class="status">
                <h2>System Status</h2>
                <div id="status-indicators">
                    <div class="status-item">
                        <span class="status-dot online"></span>
                        <span>Observable Framework</span>
                    </div>
                    <div class="status-item">
                        <span class="status-dot checking" id="grafana-status"></span>
                        <span>Grafana</span>
                    </div>
                    <div class="status-item">
                        <span class="status-dot checking" id="quickwit-status"></span>
                        <span>Quickwit</span>
                    </div>
                    <div class="status-item">
                        <span class="status-dot checking" id="loki-status"></span>
                        <span>Loki</span>
                    </div>
                </div>
            </section>
        </main>
        
        <footer>
            <p>🔗 Built with Observable Framework for observability-k8s</p>
            <p>📅 Last updated: <span id="timestamp"></span></p>
        </footer>
        
        <script>
            // Update timestamp
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
            
            // Simple status checking (basic implementation)
            function checkServiceStatus(service, elementId) {
                // This is a simplified status indicator
                // In a real implementation, you'd make actual health checks
                setTimeout(() => {
                    document.getElementById(elementId).className = 'status-dot online';
                }, Math.random() * 2000 + 1000);
            }
            
            checkServiceStatus('grafana', 'grafana-status');
            checkServiceStatus('quickwit', 'quickwit-status');
            checkServiceStatus('loki', 'loki-status');
        </script>
    </body>
    </html>
  
  style.css: |
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        min-height: 100vh;
    }
    
    header {
        background: rgba(255,255,255,0.95);
        padding: 2rem;
        text-align: center;
        margin-bottom: 2rem;
        backdrop-filter: blur(10px);
    }
    
    header h1 {
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
        color: #2c3e50;
    }
    
    main {
        max-width: 1200px;
        margin: 0 auto;
        padding: 0 2rem;
    }
    
    section {
        background: rgba(255,255,255,0.95);
        margin-bottom: 2rem;
        padding: 2rem;
        border-radius: 12px;
        backdrop-filter: blur(10px);
        box-shadow: 0 8px 32px rgba(0,0,0,0.1);
    }
    
    h2 {
        color: #2c3e50;
        margin-bottom: 1.5rem;
        font-size: 1.8rem;
    }
    
    .links-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 1.5rem;
    }
    
    .service-link {
        display: block;
        padding: 1.5rem;
        text-decoration: none;
        color: white;
        border-radius: 8px;
        transition: transform 0.2s ease;
    }
    
    .service-link:hover {
        transform: translateY(-4px);
    }
    
    .grafana { background: linear-gradient(135deg, #ff6b35, #f7931e); }
    .quickwit { background: linear-gradient(135deg, #4facfe, #00f2fe); }
    .argocd { background: linear-gradient(135deg, #43e97b, #38f9d7); }
    .loki { background: linear-gradient(135deg, #667eea, #764ba2); }
    
    .service-link h3 {
        margin-bottom: 0.5rem;
        font-size: 1.2rem;
    }
    
    .sources-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 1rem;
    }
    
    .source-card {
        padding: 1.5rem;
        border-left: 4px solid #667eea;
        background: #f8f9fa;
        border-radius: 4px;
    }
    
    .endpoint {
        font-family: 'Courier New', monospace;
        background: #e9ecef;
        padding: 0.2rem 0.5rem;
        border-radius: 4px;
        font-size: 0.9rem;
    }
    
    .architecture-diagram pre {
        background: #f8f9fa;
        padding: 1.5rem;
        border-radius: 8px;
        overflow-x: auto;
        font-family: 'Courier New', monospace;
        color: #495057;
    }
    
    #status-indicators {
        display: flex;
        flex-wrap: wrap;
        gap: 2rem;
    }
    
    .status-item {
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }
    
    .status-dot {
        width: 12px;
        height: 12px;
        border-radius: 50%;
        display: inline-block;
    }
    
    .status-dot.online { background: #28a745; }
    .status-dot.offline { background: #dc3545; }
    .status-dot.checking { 
        background: #ffc107; 
        animation: pulse 1.5s infinite;
    }
    
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.5; }
    }
    
    footer {
        text-align: center;
        padding: 2rem;
        color: white;
        margin-top: 2rem;
    }
    
    @media (max-width: 768px) {
        header h1 { font-size: 2rem; }
        main { padding: 0 1rem; }
        section { padding: 1.5rem; }
        .links-grid { grid-template-columns: 1fr; }
    }
