---
apiVersion: v1
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2025-06-27
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://localhost:9093

    frontend:
      encoding: protobuf

    analytics:
      reporting_enabled: false

    limits_config:
      retention_period: 168h
      retention_deletes_enabled: true
      max_cache_freshness_per_query: 10m

    compactor:
      working_directory: /tmp/loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: loki:/ConfigMap:loki-system/loki-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"loki.yaml":"auth_enabled: false\n\nserver:\n  http_listen_port: 3100\n  grpc_listen_port: 9096\n\ncommon:\n  instance_addr: 127.0.0.1\n  path_prefix: /tmp/loki\n  storage:\n    filesystem:\n      chunks_directory: /tmp/loki/chunks\n      rules_directory: /tmp/loki/rules\n  replication_factor: 1\n  ring:\n    kvstore:\n      store: inmemory\n\nquery_range:\n  results_cache:\n    cache:\n      embedded_cache:\n        enabled: true\n        max_size_mb: 100\n\nschema_config:\n  configs:\n    - from: 2020-10-24\n      store: boltdb-shipper\n      object_store: filesystem\n      schema: v11\n      index:\n        prefix: index_\n        period: 24h\n\nruler:\n  alertmanager_url: http://localhost:9093\n\nfrontend:\n  encoding: protobuf\n\nanalytics:\n  reporting_enabled: false\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"loki:/ConfigMap:loki-system/loki-config"},"name":"loki-config","namespace":"loki-system"}}
  creationTimestamp: "2025-06-27T11:38:08Z"
  name: loki-config
  namespace: loki-system
  resourceVersion: "30808"
  uid: a54c5229-f474-48fc-93a6-89bf9adc52bc
