---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector-system  # Using same namespace for easy replacement

resources:
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
  # Note: We're reusing the existing vector-rbac.yaml service account