apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/norandom/observability-k8s.git
    targetRevision: HEAD
    path: apps/fluent-bit
  destination:
    server: https://kubernetes.default.svc
    namespace: vector-system  # Using same namespace for easy replacement
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true