apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/norandom/observability-k8s.git
    targetRevision: HEAD
    path: apps/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: loki-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
