apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.30.1
    chart: loki
    helm:
      valueFiles:
      - values.yaml
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          querier:
            max_concurrent: 2
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
            retention_period: 720h
            retention_deletes_enabled: true
        deploymentMode: Distributed
        ingester:
          replicas: 1
          zoneAwareReplication:
            enabled: false
        querier:
          replicas: 1
          maxUnavailable: 0
        queryFrontend:
          replicas: 1
          maxUnavailable: 0
        queryScheduler:
          replicas: 1
        distributor:
          replicas: 1
          maxUnavailable: 0
        compactor:
          replicas: 1
        indexGateway:
          replicas: 1
          maxUnavailable: 0
        bloomPlanner:
          replicas: 0
        bloomBuilder:
          replicas: 0
        bloomGateway:
          replicas: 0
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        singleBinary:
          replicas: 0
        gateway:
          service:
            type: LoadBalancer
        minio:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: loki-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true