apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observable
  namespace: argocd
  labels:
    app.kubernetes.io/name: observable
    app.kubernetes.io/component: dashboard
spec:
  project: default
  source:
    repoURL: https://github.com/norandom/observability-k8s.git
    targetRevision: HEAD
    path: apps/observable
  destination:
    server: https://kubernetes.default.svc
    namespace: observable
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true