apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/observability-k8s.git
    targetRevision: HEAD
    path: apps/otel
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true