---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: vector-system
  labels:
    app: vector
    component: log-collector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
        component: log-collector
    spec:
      serviceAccountName: vector
      tolerations:
        # Allow running on master nodes
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: vector
          image: vectordotdev/vector:0.39.0-debian
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: api
              containerPort: 8686
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            # Vector configuration
            - name: config
              mountPath: /etc/vector
              readOnly: true
            # Data directory for Vector state
            - name: data
              mountPath: /var/lib/vector
            # Host paths for log collection
            - name: var-log
              mountPath: /var/log
              readOnly: true
            - name: var-lib-docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: var-log-pods
              mountPath: /var/log/pods
              readOnly: true
            # Journald socket
            - name: systemd-journal
              mountPath: /run/log/journal
              readOnly: true
          securityContext:
            privileged: false
            runAsUser: 0  # Required to read host logs
            capabilities:
              drop:
                - ALL
              add:
                - DAC_OVERRIDE  # Required to read log files
          livenessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8686
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: vector-config
        - name: data
          emptyDir: {}
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker-containers
          hostPath:
            path: /var/lib/docker/containers
        - name: var-log-pods
          hostPath:
            path: /var/log/pods
        - name: systemd-journal
          hostPath:
            path: /run/log/journal
      # Ensure Vector runs on every node
      hostNetwork: false
      dnsPolicy: ClusterFirst
