apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: vector-system
  labels:
    app: vector
spec:
  selector:
    app: vector
  ports:
    - name: api
      port: 8686
      targetPort: 8686
      protocol: TCP
  type: ClusterIP