---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickwit
  namespace: quickwit-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickwit
  template:
    metadata:
      labels:
        app: quickwit
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: quickwit
        image: quickwit/quickwit:0.7.1
        command: ["quickwit", "run"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 7280
        volumeMounts:
        - name: config
          mountPath: /quickwit/config
        - name: data
          mountPath: /quickwit/qwdata
        env:
        - name: QW_CONFIG
          value: /quickwit/config/quickwit.yaml
      volumes:
      - name: config
        configMap:
          name: quickwit-config
      - name: data
        persistentVolumeClaim:
          claimName: quickwit-pvc
