apiVersion: v1
kind: ConfigMap
metadata:
  name: quickwit-config
  namespace: quickwit-system
data:
  quickwit.yaml: |
    version: 0.7
    node_id: quickwit-node
    listen_address: 0.0.0.0:7280
    rest_listen_port: 7280
    grpc_listen_port: 7281
    data_dir: /quickwit/qwdata
    default_index_root_uri: file:///quickwit/qwdata/indexes
