apiVersion: batch/v1
kind: CronJob
metadata:
  name: quickwit-storage-cleanup
  namespace: quickwit-system
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: curlimages/curl:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              set -e
              echo "Starting Quickwit storage cleanup check..."
              
              # Get current disk usage from Quickwit API
              QUICKWIT_URL="http://quickwit.quickwit-system.svc.cluster.local:7280"
              
              # Check if we can reach Quickwit
              if ! curl -s -f "$QUICKWIT_URL/health" > /dev/null; then
                echo "Cannot reach Quickwit service, skipping cleanup"
                exit 0
              fi
              
              # Get index stats to check storage usage
              INDEX_STATS=$(curl -s "$QUICKWIT_URL/api/v1/otel-logs-v0_7/stats" || echo '{}')
              echo "Index stats: $INDEX_STATS"
              
              # Check if storage usage is approaching limit (5.5GB out of 6GB)
              # This is a simplified check - in production you'd parse the actual storage metrics
              echo "Storage cleanup check completed"
            env:
            - name: MAX_STORAGE_GB
              value: "6"
            - name: CLEANUP_THRESHOLD_GB
              value: "5.5"