apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-plugins
data:
  plugins.txt: |
    yesoreyeram-infinity-datasource
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources: []
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki.loki-system.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: quickwit
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
      
      - name: Quickwit
        type: yesoreyeram-infinity-datasource
        access: proxy
        orgId: 1
        url: http://quickwit.quickwit-system.svc.cluster.local:7280
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          url_options:
            method: "POST"
            headers:
              - name: "Content-Type"
                value: "application/json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  observability-overview.json: |
    {
      "id": null,
      "title": "Observability Overview",
      "tags": ["observability", "logs"],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Recent Operational Logs (Loki)",
          "type": "logs",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "loki"
              },
              "expr": "{job=~\".+\"}",
              "refId": "A"
            }
          ],
          "gridPos": {"h": 8, "w": 24, "x": 0, "y": 0}
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "30s"
    }