apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-plugins
data:
  plugins.txt: |
    yesoreyeram-infinity-datasource
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources: []
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki.loki-system.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: quickwit
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
      
      - name: Quickwit
        type: yesoreyeram-infinity-datasource
        access: proxy
        orgId: 1
        url: http://quickwit.quickwit-system.svc.cluster.local:7280
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
          datasource_mode: "basic"
          global_queries:
            - name: "All Logs"
              url: "/api/v1/otel-logs-v0_7/search"
              url_options:
                method: "POST"
                headers:
                  - name: "Content-Type"
                    value: "application/json"
                body_type: "raw"
                body_content_type: "application/json"
                body: '{"query": "*", "max_hits": 50}'
              parser: "backend"
              source: "url"
              format: "table"
              root_selector: "$.hits"
              columns:
                - selector: "timestamp"
                  text: "Time"
                  type: "timestamp_epoch_s"
                - selector: "body"
                  text: "Message"
                  type: "string"
                - selector: "log_type"
                  text: "Type"
                  type: "string"
                - selector: "severity_text"
                  text: "Level"
                  type: "string"
                - selector: "service_name"
                  text: "Service"
                  type: "string"
            - name: "Security Logs"
              url: "/api/v1/otel-logs-v0_7/search"
              url_options:
                method: "POST"
                headers:
                  - name: "Content-Type"
                    value: "application/json"
                body_type: "raw"
                body_content_type: "application/json"
                body: '{"query": "log_type:security", "max_hits": 100}'
              parser: "backend"
              source: "url"
              format: "table"
              root_selector: "$.hits"
              columns:
                - selector: "timestamp"
                  text: "Time"
                  type: "timestamp_epoch_s"
                - selector: "body"
                  text: "Message"
                  type: "string"
                - selector: "log_type"
                  text: "Type"
                  type: "string"
                - selector: "severity_text"
                  text: "Level"
                  type: "string"
                - selector: "service_name"
                  text: "Service"
                  type: "string"
            - name: "Auth Logs"
              url: "/api/v1/otel-logs-v0_7/search"
              url_options:
                method: "POST"
                headers:
                  - name: "Content-Type"
                    value: "application/json"
                body_type: "raw"
                body_content_type: "application/json"
                body: '{"query": "category:auth", "max_hits": 100}'
              parser: "backend"
              source: "url"
              format: "table"
              root_selector: "$.hits"
              columns:
                - selector: "timestamp"
                  text: "Time"
                  type: "timestamp_epoch_s"
                - selector: "body"
                  text: "Message"
                  type: "string"
                - selector: "category"
                  text: "Category"
                  type: "string"
                - selector: "severity_text"
                  text: "Level"
                  type: "string"
                - selector: "service_name"
                  text: "Service"
                  type: "string"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  observability-overview.json: |
    {
      "id": null,
      "title": "Observability Overview",
      "tags": ["observability", "logs"],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Recent Operational Logs (Loki)",
          "type": "logs",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "loki"
              },
              "expr": "{job=~\".+\"}",
              "refId": "A"
            }
          ],
          "gridPos": {"h": 8, "w": 24, "x": 0, "y": 0}
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "30s"
    }