apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-system

resources:
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-ingress.yaml