name: Build D2 Diagrams

on:
  push:
    branches: [ main ]
    paths:
      - 'mydocs/*.d2'
      - 'mydocs/build.sh'
      - '.github/workflows/build-diagrams.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'mydocs/*.d2'
      - 'mydocs/build.sh'

jobs:
  build-diagrams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install D2
      run: |
        curl -fsSL https://d2lang.com/install.sh | sh -s --
        sudo mv d2 /usr/local/bin/
        d2 --version
        
    - name: Create output directory
      run: mkdir -p mydocs/output
      
    - name: Build diagrams
      run: |
        cd mydocs
        chmod +x build.sh
        ./build.sh
        
    - name: Check for build errors
      run: |
        if [ -f mydocs/error.log ] && grep -q "\[ERROR\]" mydocs/error.log; then
          echo "Build errors found:"
          cat mydocs/error.log
          exit 1
        fi
        
    - name: Display build results
      run: |
        echo "Generated files:"
        ls -la mydocs/output/ || echo "No output files generated"
        
    - name: Configure Git
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push built diagrams
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git add mydocs/output/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-build D2 diagrams

          Generated from D2 source files in mydocs/
          
          🤖 Generated by GitHub Actions
          
          Files updated:
          $(ls mydocs/output/ 2>/dev/null | sed 's/^/- /' || echo '- No files generated')"
          
          git push
        fi
        
    - name: Upload diagrams as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: d2-diagrams
        path: mydocs/output/
        retention-days: 30
        
    - name: Comment on PR with diagram links
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if output directory exists and has files
          const outputDir = 'mydocs/output';
          if (!fs.existsSync(outputDir)) {
            console.log('No output directory found');
            return;
          }
          
          const files = fs.readdirSync(outputDir);
          if (files.length === 0) {
            console.log('No diagram files generated');
            return;
          }
          
          const diagrams = files.filter(f => f.endsWith('.png') || f.endsWith('.svg'));
          
          if (diagrams.length > 0) {
            const body = `## 📊 Generated Diagrams
            
            The following diagrams were generated from your D2 source files:
            
            ${diagrams.map(file => `- \`${file}\``).join('\n')}
            
            **Download all diagrams**: The diagrams are available as build artifacts.
            
            **To view locally**: Run \`cd mydocs && ./build.sh\` after merging.
            
            ---
            🤖 *Auto-generated by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
          }