name: Fix YAML Lint Issues

on:
  workflow_dispatch:  # Allow manual trigger
  
jobs:
  fix-yaml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install yamllint
      run: pip install yamllint
      
    - name: Run comprehensive YAML fix
      run: |
        # Fix common YAML issues
        echo "Fixing YAML lint issues..."
        
        # Remove trailing whitespace and ensure files end with newline
        find apps/ -name "*.yaml" -o -name "*.yml" | while read file; do
          echo "Fixing: $file"
          # Remove trailing spaces
          sed -i 's/[[:space:]]*$//' "$file"
          # Ensure file ends with newline
          [ -n "$(tail -c1 "$file")" ] && echo >> "$file"
        done
        
        # Fix specific indentation issues
        echo "Fixing specific indentation issues..."
        
        # Fix yamllint errors by reprocessing with proper indentation
        python3 << 'EOF'
        import re
        import os
        
        def fix_yaml_indentation(filepath):
            with open(filepath, 'r') as f:
                content = f.read()
            
            lines = content.split('\n')
            fixed_lines = []
            
            for i, line in enumerate(lines):
                # Skip empty lines
                if not line.strip():
                    fixed_lines.append(line)
                    continue
                
                # Basic indentation fixes for common patterns
                if re.match(r'^(\s*)-\s+\w+:', line):  # List items
                    # Ensure proper spacing after dash
                    indent = len(line) - len(line.lstrip())
                    content_after_dash = line.lstrip()[1:].lstrip()
                    fixed_lines.append(' ' * indent + '- ' + content_after_dash)
                elif re.match(r'^(\s*)\w+:\s*$', line):  # Keys with no value
                    fixed_lines.append(line)
                else:
                    fixed_lines.append(line)
            
            with open(filepath, 'w') as f:
                f.write('\n'.join(fixed_lines))
        
        # Process YAML files in apps directory
        for root, dirs, files in os.walk('apps'):
            for file in files:
                if file.endswith(('.yaml', '.yml')):
                    filepath = os.path.join(root, file)
                    try:
                        fix_yaml_indentation(filepath)
                        print(f"Processed: {filepath}")
                    except Exception as e:
                        print(f"Error processing {filepath}: {e}")
        EOF
        
    - name: Test YAML syntax
      run: |
        echo "Testing YAML files for syntax errors..."
        yamllint -c .yamllint.yml apps/ || echo "YAML lint issues remain - manual review needed"
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - YAML Fixer"
        
    - name: Commit fixes
      run: |
        git add apps/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Fix YAML lint issues

          - Remove trailing whitespace
          - Fix indentation errors
          - Ensure files end with newlines
          - Address yamllint rule violations
          
          🤖 Auto-fixed by GitHub Actions"
          
          git push
        fi